import "./globals.css";
import { Inter } from "next/font/google";
import Link from 'next/link'

const inter = Inter({ subsets: ["latin"] });

const menus = [
  {
    id: 1,
    name: "Pedidos de Compra",
    url: "pedidos/",
  },
  {
    id: 2,
    name: "Cambiar Clave",
    url: "changePassword/",
  },
  {
    id: 3,
    name: "Confirmacion Mail",
    url: "sendMail/",
  },
  {
    id: 4,
    name: "Login",
    url: "login/",
  },
  {
    id: 5,
    name: "Account",
    url: "account/",
  },
];

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@300;500;700&family=Roboto:wght@300&display=swap" rel="stylesheet" />
      </head>
      <body className={inter.className}>
        <header>
          <nav>
            <ul>
              <li>
                <Link href="/">
                  <div>
                    <span>
                      Logo
                    </span>
                  </div>
                </Link>
              </li>
              <li>
                {menus.map(({ id, name, url }) => (
                  <Link key={id} href={url}>{name}</Link>
                ))}
              </li>
              <li>
                <Link href="#">
                  <div>
                    <span>
                      User
                    </span>
                  </div>
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}</body>
    </html>
  );
}
